<main id="home">
    <section class="homepage">
        <h1>Étudiant développeur FullStack</h1>
        <h2>Félix Parendeau Millerioux</h2>
        <div>
            <a href="mailto:felix.parendeau@gmail.com">
                <i class="fa-regular fa-envelope"></i>
                <p>felix.parendeau@gmail.com</p>
            </a>
            <a href="https://www.linkedin.com/in/felix-parendeau/" target="_blank">
                <i class="fa-brands fa-linkedin"></i>
                <p>linkedin.com/in/felix-parendeau</p>
            </a>
            <a href="tel:0767403267">
                <i class="fa-solid fa-phone-flip"></i>
                <p>07 67 40 32 67</p>
            </a>
            <a target="_blank" href="https://www.google.fr/maps/place/Orl%C3%A9ans/@47.8733878,1.8298142,12z/data=!3m1!4b1!4m6!3m5!1s0x47e4e4d49df386e3:0x9eb97de479c38029!8m2!3d47.9032335!4d1.9085203!16zL20vMGsxcDg?entry=ttu&g_ep=EgoyMDI2MDExMy4wIKXMDSoASAFQAw%3D%3D">
                <i class="fa-solid fa-location-dot"></i>
                <p>Orléans, France</p>
            </a>
        </div>
        <a href="index.php?path=projets" class="btn">Voir mes projets</a>
    </section>
</main>