<main id="links">
    <ul class="social-links">
        <h2 class="txt-links">Liens de contact</h2>
        <div class='liens-contact' style="display: flex;">
            <li>
                <a href="https://www.instagram.com/_felix_pm/?utm_source=qr#" target="_blank">
                    <i class="fa-brands fa-instagram"></i>
                </a>
            </li>
            <li>
                <a href="https://github.com/felix-pm" target="_blank">
                    <i class="fa-brands fa-github"></i>
                </a>
            </li>
            <li>
                <a href="https://www.linkedin.com/in/felix-parendeau/" target="_blank">
                    <i class="fa-brands fa-linkedin"></i>
                </a>
            </li>
        </div>
        <li>
            <div class="txt-call" style="display: flex;">
                <a href="mailto:felix.parendeau@gmail.com" class="div-hover">
                    <i class="fa-regular fa-envelope"></i>
                    <p>felix.parendeau@gmail.com</p>
                </a>
                <a href="tel:0767403267" class="div-hover">
                    <i class="fa-solid fa-phone-flip"></i>
                    <p>07 67 40 32 67</p>
                </a>
            </div>
        </li>
    </ul>
</main>