<main id="home">
    <section class="homepage">
        <h1>Étudiant développeur FullStack</h1>
        <h2>Félix Parendeau Millerioux</h2>
        <div>
            <a href="">
                <i class="fa-regular fa-envelope"></i>
                <p>felix.parendeau@gmail.com</p>
            </a>
            <a href="">
                <i class="fa-brands fa-linkedin"></i>
                <p>linkedin.com/in/felix-parendeau</p>
            </a>
            <a href="">
                <i class="fa-solid fa-phone-flip"></i>
                <p>07 67 40 32 67</p>
            </a>
            <a href="">
                <i class="fa-solid fa-location-dot"></i>
                <p>Orléans, France</p>
            </a>
        </div>
        <a href="index.php?path=projets" class="btn">Voir mes projets</a>
    </section>
</main>