<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= isset($titre) ? $titre : "Mon Portfolio" ?></title>
    
    <link rel="stylesheet" href="assets/css/style.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>
<body>

    <header>
        <nav>
            <a href="assets/cv_felix_pm.pdf" class="btn" download target="_blank">Télécharger mon CV</a>
            <ul>
                <li><a href="index.php?path=home">Accueil</a></li>
                <li><a href="index.php?path=experiences">Expériences</a></li>
                <li><a href="index.php?path=skills">Skills</a></li>
                <li><a href="index.php?path=projets">Projets</a></li>
                <li><a href="index.php?path=links">Liens</a></li>
            </ul>
        </nav>
    </header>

    <div class="container">
        <?php require "templates/" . $template . ".phtml"; ?>
    </div>

    <?php require "templates/footer.phtml"; ?>

</body>
</html>