<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= isset($titre) ? $titre : "Mon Portfolio" ?></title>
    
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>

    <header>
        <nav>
            <a href="https://www.linkedin.com/in/felix-parendeau/" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
            <a href="https://github.com/felix-pm"><i class="fa-brands fa-github" target="_blank"></i></a>
            <a href="assets/cv_felix_pm.pdf" class="btn" download target="_blank">Télécharger mon CV</a>
            <ul>
                <li><a href="#home">Accueil</a></li>
                <li><a href="#experiences">Expériences</a></li>
                <li><a href="#skills">Skills</a></li>
                <li><a href="#projets">Projets</a></li>
                <li><a href="#links">Liens</a></li>
            </ul>
        </nav>
    </header>

    <?php require "templates/partials/home.phtml"; ?>
    <?php require "templates/partials/experiences.phtml"; ?>
    <?php require "templates/partials/skills.phtml"; ?>
    <?php require "templates/partials/projets.phtml"; ?>
    <?php require "templates/partials/links.phtml"; ?>

    <img src="assets/img/moi.png" alt="Moi" class="photo-moi">

    <script src="assets/js/nav.js"></script>

</body>
</html>