<main id="links">
    <h2>Liens de contact</h2>
    <ul class="social-links">
        <div class='liens-contact' style="display: flex;">
            <li>
                <a href="https://www.instagram.com/_felix_pm/?utm_source=qr#" target="_blank">
                    <i class="fa-brands fa-instagram"></i>
                </a>
            </li>
            <li>
                <a href="https://github.com/felix-pm" target="_blank">
                    <i class="fa-brands fa-github"></i>
                </a>
            </li>
            <li>
                <a href="https://www.linkedin.com/in/felix-parendeau/" target="_blank">
                    <i class="fa-brands fa-linkedin"></i>
                </a>
            </li>
        </div>
        <li>
            <a href="mailto:felix.parendeau@gmail.com">
                <i class="fa-regular fa-envelope"></i>
                <p>felix.parendeau@gmail.com</p>
            </a>
            <a href="tel:0767403267">
                <i class="fa-solid fa-phone-flip"></i>
                <p>07 67 40 32 67</p>
            </a>
        </li>
    </ul>
    <img src="assets/img/moi.png" alt="Moi" class="photo-moi">
</main>